version: '3.8'

services:
  sridurga-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sridurga-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPass123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sridurga-mssql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sridurga-mssql-data:
