services:
  sridurga-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sridurga-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPass123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sridurga-mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"YourStrongPass123!\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  sridurga-mssql-data:
